"""Add activity logs table

Revision ID: 5da10e352fc9
Revises: bd5e85ecd083
Create Date: 2025-07-29 05:41:52.126970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da10e352fc9'
down_revision = 'bd5e85ecd083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('rejection_comment')

    # ### end Alembic commands ###
