"""Add detailed fields to Request model

Revision ID: bd5e85ecd083
Revises: 10bf25c9f6c8
Create Date: 2025-07-28 20:42:14.469179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5e85ecd083'
down_revision = '10bf25c9f6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('justification', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('asset_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('asset_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('issue_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fulfilled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finance_approved', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('finance_approved')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('fulfilled_at')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('issue_description')
        batch_op.drop_column('brand')
        batch_op.drop_column('asset_description')
        batch_op.drop_column('asset_name')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('justification')
        batch_op.drop_column('reason')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
