"""Add image_url to asset

Revision ID: 7b526d8b5688
Revises: a17062528307
Create Date: 2025-07-24 05:40:14.825870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b526d8b5688'
down_revision = 'a17062528307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    """ with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True)) 
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True)) """

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.drop_table('asset_images')
    # ### end Alembic commands ###
